### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by slang25** [oss-serverless/serverless#12]
@mnapoli @j0k3r Hi folks

I stumbled on this fork this week and really like the changes made, i.e. v3 Serverless Framework that remains compatible, removes cruft, gets security patches etc...

I'm interested to know a little more about who the maintainers are, is this intended to be a "community fork", are you looking for contributors or additional maintainers, what's your stance on adding features vs resisting development etc...

I guess this was created to fit your teams/companies need, but how open are you for wider adoption?

**Comment by mnapoli** [comment]
Thanks for the questions! I've tried to clarify this in the README directly:

https://github.com/oss-serverless/serverless/commit/483586efaca65a4eabfc431e2e169d2e0aeff7f5

> The repository has been created and is maintained by [Bref](https://bref.sh) maintainers and contributors. The main goal of this repository is to provide continuity for Bref users, so that these Bref projects keep working for the next 5 years. No major new features are planned. However, community contributions to keep the project running (even for languages other than PHP), like adding support to new runtime versions, adapting to AWS changes, bugfixes, and other small improvements are welcome.

Does that answer the questions?

**Comment by slang25** [comment]
That is spot on @mnapoli, thank you for adding this clarification 🙂

**Comment by seanspeaks** [comment]
@mnapoli I run the Frigg Framework open source project, and we've been based on serverless since day one. I've got a long-standing backlog item to migrate to Pulumi or Open Tofu, but not having to do that in favor of the forked serverless both saves time and likely speeds up delivery of a more stable set of versions for me.

So, question... are you open to collaborating more deeply on it? If I/we threw in different cloud provider adapters, for example, or unified the local running so that it didn't matter what host provider you chose, `serverless offline` just ran as expected, would that be acceptable? It seems like it may expand the scope of your README/project goals, which is why I'm asking in this thread.

Happy to do a quick call to discuss too, probably easier to unpack 👍
